version: 2

sources:
  - name: erp
    schema: sap_adw
    description: Fonte de dados do ERP da Adventure Works.
    tables:
      - name: customer
        description: Informações atuais do cliente.
        columns:
          - name: customerid
            description: Chave primária da tabela de clientes.
            tests:
              - unique
              - not_null

      - name: person
        description: Informações de dados pessoais.
        columns:
          - name: BusinessEntityID
            description: Chave primária para registros de pessoas,
            tests:
              - unique
              - not_null

      - name: address
        description: Informações sobre os endereços.
        columns:
          - name: addressID
            description: Chave primária para registros de endereço.
            tests:
              - unique
              - not_null
          - name: city
            description: Nome da Cidade        
          - name: stateprovinceid
            description: ID do estado

      - name: product
        description: Informações sobre os produtos.
        columns:
          - name: productid
            description: Chave primária para registros de produtos.
            tests:
              - unique
              - not_null
          - name: name
            description: Nome do produto.

      - name: stateprovince
        description: Informações sobre os estados.
        columns:
          - name: stateprovinceid
            description: Chave primária para registros de estados.
            tests:
              - unique
              - not_null
          - name: stateprovincecode
            description: Código do Estado
          - name: countryregioncode
            description: Código do País.
          - name: name
            description: Nome do estado.


      - name: countryregion
        description: Informações sobre os produtos.
        columns:
          - name: countryregioncode
            description: Chave primária para registros de país.
            tests:
              - unique
              - not_null
          - name: name
            description: Nome do país.



      - name: personcreditcard
        description: Informações sobre os cartão de crédito.
        columns:
          - name: businessentityid
            description: Chave primária da Entidade de Negócios.
            tests:
              - unique
              - not_null
          - name: creditcardid
            description: Chave estrangeira da tabela Cartão de Crédito.

      - name: creditcard
        description: Informações sobre os registros de Cartão de Crédito.
        columns:
          - name: creditcardid
            description: Chave primária para registros de Cartão de Crédito.
            tests:
              - unique
              - not_null
          - name: cardtype
            description: Tipo de Cartão.

      - name: salesorderheadersalesreason
        description: Cabeçalho do motivo de venda.
        columns:
          - name: salesorderid
            description: Chave primária para registros cabeçalho do motivo de venda.
            tests:
              - unique
              - not_null
          - name: salesreasonid
            description: Id do motivo da venda.

      - name: salesreason
        description: Informações sobre os motivos de venda.
        columns:
          - name: salesreasonid
            description: Chave primária para registros de motivos de venda.
            tests:
              - unique
              - not_null
          - name: name
            description: Motivo da Venda
          - name: reasontype
            description: Tipo do motivo

      - name: salesorderheader
        description: Cabeçalho do pedido de venda.
        columns:
          - name: salesorderid
            description: Chave primária para registros de cabeçalho do pedido de venda.
            tests:
              - unique
              - not_null
          - name: orderdate
            description: sdds
          - name: duedate
            description: sdsd
          - name: status
            description: dsd
          - name: creditcardid
            description: dsdsd

      - name: salesorderdetail
        description: Detalhes dos pedidos de venda.
        columns:
          - name: salesorderid
            description: Chave primária para o pedido de venda.
            tests:
              - unique
              - not_null
          - name: salesorderdetailid
            description: Id da Venda detalhada
          - name: carriertrackingnumber
            description: Número de rastreamento da transportadora.
          - name: orderqty
            description: Quantidade do pedido.
          - name: productid
            description: ID do produto.
          - name: specialofferid
            description: ID da oferta especial.
          - name: unitprice
            description: Preço unitário.
          - name: unitpricediscount
            description: Valor do desconto.

      - name: specialofferproduct
        description: Informações sobre os produtos.
        columns:
          - name: SpecialOfferID
            description: Chave primária para registros de produtos em ofertas especiais.
            tests:
              - unique
              - not_null
          - name: productid
            description: Id do produto

      - name: specialoffer
        description: Informações sobre ofertas especiais.
        columns:
          - name: SpecialOfferID
            description: Chave primária para registros de ofertas especiais.
            tests:
              - unique
              - not_null
          - name: type
            description: Tipo de oferta


