version: 2

sources:
  - name: erp
    schema: sap_adw
    description: Fonte de dados do ERP da Adventure Works.
    tables:
      - name: customer
        description: Informações atuais do cliente.
        columns:
          - name: customerid
            description: Chave primária da tabela de clientes.
            tests:
              - unique
              - not_null

      - name: person
        description: Informações de dados pessoais.
        columns:
          - name: BusinessEntityID
            description: Chave primária para registros de pessoas,
            tests:
              - unique
              - not_null

      - name: address
        description: Informações sobre os endereços.
        columns:
          - name: addressID
            description: Chave primária para registros de endereço.
            tests:
              - unique
              - not_null
          - name: city
            description: Nome da Cidade        
          - name: stateprovinceid
            description: ID do estado