version: 2

models:
  - name: dim_clientes
    description: Dimensão de Clientes da Adventure Works.
    columns:
      # - name: pk_cliente
      #   description: Chave primaria da dimensão clientes.
      #   tests:
      #     - unique
      #     - not_null

      - name: id_cliente
        description: Chave primária da tabela de clientes.
        tests:
          - unique
          - not_null

      - name: id_pessoa
        description: Chave estrangeira para Person.BusinessEntityID